name: PR - Run Unit Tests
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    unit-test-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: git configure
              run: |
                  git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com
            - name: Run Unit Test
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
              run: |
                  npm ci
                  npm run unit
